#pragma config(Sensor, S1,     touch,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int revPerMinute = 0;
int encoderCount;



void measureRPM()
{

	nMotorEncoder[motorA] = 0;
	wait1Msec(167);
	encoderCount = nMotorEncoder [motorA];
	nxtDisplayTextLine(3,"Encoder=%d", nMotorEncoder[motorA]);
	revPerMinute = 6*((60* encoderCount / 360));
	nxtDisplayTextLine (5, "speed %d rpm", revPerMinute);


}

task main()
{
	while (true)
	{

		while(SensorValue(touch) == 1)

		{
			measureRPM();
			int potency = revPerMinute + 40;
			nxtDisplayTextLine (7, "Power %d ", potency);
		  motor[motorA] = 40 + (potency / 2);


		}

		nxtDisplayTextLine(1,"Motor Float",);
		bFloatDuringInactiveMotorPWM = true;
		nMotorEncoder[motorA] = 0;
		motor[motorA] = 0;
		wait1Msec(100);
		eraseDisplay();

	}
}
