#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int revPerMinute = 0;
int encoderCount;


void measureRPM()
{

	nMotorEncoder[motorA] = 0;
	wait1Msec(167);
	encoderCount = nMotorEncoder [motorA];
	revPerMinute = encoderCount / 360;
	nxtDisplayTextLine (5, "speed %d rpm", revPerMinute);

}


task main()
{

		while (true)
		{
			while (SensorValue(touch) == 0)    // While the Touch Sensor is inactive (hasn't been pressed):

			{

		  	measureRPM();
		   	motor[motorA] = ((revPerMinute / 2) + 40);
		  	//wait1Msec (10);

		  }


				motor[motorA] = 0;
			  //wait1Msec(10);

		}
}
