#pragma config(Sensor, S1,     touch,         sensorTouch)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Defining the variables

int revPerMinute = 0;
int encoderCount;

//Functions
//This functions measures the rotation speed of the input

void measureRPM()
{

	nMotorEncoder[motorA] = 0;																		// Initialize the rotation sensor of the servo
	wait1Msec(100);																								// Wait for 0,1 sec to measure the final angle
	encoderCount = nMotorEncoder [motorA];												// We read the angle of the serva after 167 ms
	nxtDisplayTextLine(3,"Encoder=%d", nMotorEncoder[motorA]); 		//Displaying the result
	revPerMinute = 10 *((60* encoderCount / 360));								//Converting the units
	nxtDisplayTextLine (5, "speed %d rpm", revPerMinute);					//Displaying the result

}

task main()

{

	while (true)																									//We want a forever loop

	{

		while(SensorValue(touch) == 1)															//When the accelerator is pressed

		{

			measureRPM();																							//We call the function
			//int potency = revPerMinute + 40;
			int potency = 40 + revPerMinute;													//The constants may vary
			nxtDisplayTextLine (7, "Power %d ", potency);
		  //motor[motorA] = 40 + (potency / 2);
		  motor[motorA] = (potency / 2);

		}

		//We leave the motor coasting when the button is not pressed

		nxtDisplayTextLine(1,"Motor Float",);
		bFloatDuringInactiveMotorPWM = true;
		//nMotorEncoder[motorA] = 0;
		motor[motorA] = 0;
		wait1Msec(100);
		eraseDisplay();

	}

}
