#pragma config(Sensor, S1,     armTouch,       sensorTouch)
#pragma config(Sensor, S3,     colorSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          armMotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//





void RaiseArm ()
{
  nMotorEncoder[motorA] = 0;
  while (SensorValue(armTouch) == 0)
  {
    motor[motorA] = 35;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}

void LowerArm ()
{
  while(nMotorEncoder[motorA] > 0)
  {
    motor[motorA] = -30;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}

void Drive_Forward (int speed1, int speed2)
{
  nMotorEncoder[motorB]=0;
  nMotorEncoderTarget[motorB] = 400;
  motor[motorB] = speed1;
  motor[motorC] = speed2;
  while(nMotorRunState[motorB] != runStateIdle)
  {
    // do nothing
  }



}



task main()
{
  //RaiseArm();
	//Spin();
 	//LowerArm();

 Drive_Forward(25,-25);


}
