#pragma config(Sensor, S1,     armTouch,       sensorTouch)
#pragma config(Sensor, S3,     colorSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          armMotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "C:\Program Files\Robotics Academy\ROBOTC for MINDSTORMS\Sample Programs\NXT\3rd Party Sensor Drivers\drivers/common.h"
//#include "C:\Program Files\Robotics Academy\ROBOTC for MINDSTORMS\Sample Programs\NXT\3rd Party Sensor Drivers\drivers/HTCS-driver.h"

int distance_in_cm = 30, LeftScan, CenterScan, RightScan, color1, color2;

void RaiseArm ()
{
  nMotorEncoder[motorA] = 0;
  while (SensorValue(armTouch) == 0)
  {
    motor[motorA] = 35;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}

void LowerArm ()
{
  while(nMotorEncoder[motorA] > 0)
  {
    motor[motorA] = -30;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}

void Drive_Forward (int speed1, int speed2)
{
  motor[motorB] = speed1;
  motor[motorC] = speed2;
}

/* void Scan_Object ()
{
  nMotorEncoder[motorB] = 0;
  nMotorEncoderTarget[motorB] = 100;
  motor[motorB] = 75;
  motor[motorC] = -75;
  while(nMotorRunState[motorB] != runStateIdle)
  {
    // do nothing
  }
  motor[motorB] = 0;
  motor[motorC] = 0;
  LeftScan = SensorValue(sonarSensor);
  nMotorEncoderTarget[motorB] = -200;
  motor[motorB] = -75;
  motor[motorC] = 75;
  while(nMotorRunState[motorB] != runStateIdle)
  {
    //do nothing
  }
  motor[motorB] = 0;
  motor[motorC] = 0;
  RightScan = SensorValue(sonarSensor);
  nMotorEncoder[motorB] = 0;
  nMotorEncoderTarget[motorB] = 100;
  motor[motorB] = 75;
  motor[motorC] = -75;
  while(nMotorRunState[motorB] != runStateIdle)
  {
    // do nothing
  }
  motor[motorB] = 0;
  motor[motorC] = 0;

  if (LeftScan > (CenterScan - 5) && LeftScan < (CenterScan + 5) && RightScan > (CenterScan - 5) && RightScan < (CenterScan + 5))
  {
    // object too large - backup and change direction
    Drive_Forward (-45, -45);
    wait1Msec(3000);
    motor[motorB] = 0;
    motor[motorC] = 0;
  }
  else
  {
    LowerArm();
    Drive_Forward (45, 45);
    wait1Msec(1000);
    _color = HTCSreadColor(colorSensor);
    if (_color == 2)
    {
      RaiseArm();
    }
    else
    {
      Drive_Forward (-45, -45);
      wait1Msec(1000);
      Drive_Forward (-45, 45);
      wait1Msec(500);
      RaiseArm();
    }
  }
}
*/

void Spin()
{
  while (SensorValue(sonarSensor) > 45)
    {
      //color1 = HTCSreadColor(colorSensor);
      CenterScan = SensorValue(sonarSensor);
      Drive_Forward(25, -25);
    }
  wait1Msec(200);
  Drive_Forward(0, 0);
}

task main()
{
  RaiseArm();
//  Spin();
 LowerArm();
/*  while (HTCSreadColor(colorSensor)== 0)
  {
      Drive_Forward(45, 45);
  }
  Drive_Forward(0, 0);
  */
}
