#pragma config(Sensor, S1,     armTouch,       sensorTouch)
#pragma config(Sensor, S3,     colorSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          armMotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motor B --> Right Motor
// Motor C --> Left Motor

//INITIALIZING THE VARIABLES

int distance;														//Variable used to store the value of the sound sensor
int closest = 255;											//Variable used



// FUNTION USED TO GRAB OBJECTS
// WE NEED TO EXECUTE THIS FOR THE SOUND SENSOR TO WORK

void RaiseArm ()
{
  nMotorEncoder[motorA] = 0;
  while (SensorValue(armTouch) == 0)
  {
    motor[motorA] = 35;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}


// FUNCTION USED TO RELEASE OBJECTS
// IN ORDER FOR IT TO WORK WE MUST HAVE EXECUTED RaiseArm FIRST
void LowerArm ()
{
  while(nMotorEncoder[motorA] > 0)
  {
    motor[motorA] = -30;
  }
  motor[motorA] = 0;
  wait1Msec(100);
}


// FUNCTION THAT MOVES THE ROBOT TOWARDS THE CLOSEST DETECTED OBJECT
// DEPENDING ON THE SOUND SENSOR VALUES

void Move_Closer_Sound (int speed, int range)
{
	nSyncedMotors = synchCB;															//Syncronizing the motors
	nSyncedTurnRatio = 100; 															//We want to follow a Straight line, no need for a varaible here

	while (SensorValue [sonarSensor] > range)
  {
   	motor[motorC] = speed;
  }
	  motor[motorB] = 0;
	  motor[motorC] = 0;
}


// FUNCTION THAT MOVES THE ROBOT
// THE SPEED AND HEADING ARE CONTROLLED BY THE THE VARIABLES "speed" and "synch_ratio"

void Move (int speed, int synch_ratio, int centimeters)
{

	nSyncedMotors = synchCB;															//Syncronizing the motors
	nSyncedTurnRatio = synch_ratio; 											//Contolling the heading

	nMotorEncoder[motorC]=0;															//Initialize the encoder
  nMotorEncoderTarget[motorC] = (34 * centimeters);  		//We use 34 as is the number of degress used per cm

  while(nMotorEncoder[motorC] < (34 * centimeters))			//Until you haven't reached your target keep going
  {
   	motor[motorC] = speed;
  }

	motor[motorC] = 0;																		//Stop once you are done
}



/*FUNCTION THAT ALIGNS THE SNATCHER WIHT ITS GOAL*/

int Localize(int degrees_left, int search_range, int search_speed )
{
	//distance = 0;
	//int closest = 255;
	int direction = 0;

	nSyncedMotors = synchCB;																//Syncronizing the motors
	nSyncedTurnRatio = -100; 																//We want the robot to spin

	// Moving the snatcher to the left to start searching
	nMotorEncoder[motorC]=0;																//Initializing the encoder
  nMotorEncoderTarget[motorC] = degrees_left;							//Setting target

  motor[motorC] = -search_speed;													//Setting motor power

  while(nMotorRunState[motorC] != runStateIdle)						//Wait till we are done
  {
    // do nothing
  }

	motor[motorC]= 0;																				//Stop the motors
	wait10Msec(100);

	// Starting the search now
  nMotorEncoder[motorC]= 0;																//Using motor C encoder to search
  nMotorEncoderTarget [motorC]= search_range;

  while (nMotorEncoder[motorC] < search_range)
  {
  	distance = SensorValue[sonarSensor];

  	motor[motorC] = search_speed;

  	if (distance < closest)																//Working out where to closest object is
  	{
  		closest = distance;
  		direction = nMotorEncoder[motorC];									//Saving the position of the closest object
  		nxtDisplayTextLine(4,"direction: %d", direction);
  		nxtDisplayTextLine(2,"Closest: %d", closest);
  	}

	}

	motor[motorC]= 0;																					//Stopping everything once we are done
  wait10Msec(50);

  while (nMotorEncoder[motorC]> direction)									//Aligning the Robot with the object
  {
  	motor[motorC]= -search_speed;
  }

  motor[motorC]= 0;
  wait10Msec(50);
  return closest;
}


task main()
{
  bFloatDuringInactiveMotorPWM = false; 						// This is on by default

	RaiseArm();
  Localize(400, 800, 25);

  if (closest< 25)
  {
  	Localize (200, 400, 20);
  	LowerArm();
  	Move(25, 100, 15);
  	RaiseArm();
	  Move(-25, 100, -20);
	  Move(25, -100, 15);
	  LowerArm();
  }

  else
	{
		Move_Closer_Sound(15, 25);
		Localize(200, 400, 20);
		LowerArm();
	  Move(25, 100, 15);
	  RaiseArm();
	  Move(-25, 100, -20);
	  Move(25, -100, 15);
	  LowerArm();
	}

}
