#pragma config(Sensor, S1,     radar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int valor_posicion= nMotorEncoder[motorA];

int giroAngulo = 100;

/*The first part of the program is responsible for rotating the head with the sensor on it back and forth and for preparing the
progress bar on the NXT's display.  This happens over and over again inside of a while loop
*/
void moveRadarForward()
{

	nMotorEncoder[motorA]=0;

/*Since the gears on the radar require the motor to turn 5 turns for every full turn of the
head, we turn the motor by 1000 degrees, which results in a head rotation of 1000 / 5 = 200 degrees.
*/

	nMotorEncoderTarget[motorA]= giroAngulo; //Moving clockwise

		nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
		nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)
		motor[motorA]=25;

	//	wait10Msec(10)


}
task main()
{

	while (true)
	{
		moveRadarForward();
	}


}
